# A first stab at a grammar which will evolve an update algorithm for a
# heterogenous cellular network.

<expr> ::= <reg> | <reg> | <reg> | <val> <op> <val> | <val>

<reg> ::= (<expr> <op> <expr>) | (<expr> <op> <expr>) | (<expr> <op> <expr>) | <div>(<expr>, <expr>)
#| <fn>(<expr>) | <fn>(<expr>) | <fn>(<expr>) | <spfn> | <spfn>

<op> ::= + | - | *

<div> ::= self.pdiv

<plog> ::= log(abs(<expr>) + 1)

<sqrt> ::= sqrt(abs(<expr>))

<spfn> ::= <plog> | <sqrt>

<fn> ::= sin | cos | tan

<val> ::= ABS_MSUEs | non_ABS_MUEs | ABS_MUEs | <epsilon>

<epsilon> ::= float('<n>')

#| float('<n><n><n>.<n><n><n>')

<n> ::= 0|1|2|3|4|5|6|7|8|9