<RE>             ::=            <simple-RE>|<char>
<simple-RE>      ::=            <concatenation>|<basic-RE>|<possessive>

<concatenation>  ::=            <simple-RE><basic-RE>
<basic-RE>       ::=            <elementary-RE>|<char>

<possessive>     ::=            <dot>|<starplus>|<pplus>|<qplus>|<brak>
<dot>            ::=            <elementary-RE>"."
<starplus>       ::=            <elementary-RE>"*+"
<pplus>          ::=            <elementary-RE>"++"
<qplus>          ::=            <elementary-RE>"?+"
<brak>           ::=            <RE>"{"<RE>","<RE>"}+"

<greedy>         ::=            <star>|<plus>|<question>
<star>           ::=            <elementary-RE>"*"
<plus>           ::=            <elementary-RE>"+"
<question>       ::=            <elementary-RE>"?"

<noncapgroup>    ::=            "(?:"<RE>")"
<lookarounds>    ::=            "(?<="<RE>")"| "?<!"<RE>")"|"?="<RE>")"|"?!"<RE>")" 


<elementary-RE>  ::=            <union>|<group>|<eos>|<char>|<set>|<charclass>|<rangeU>|<rangeL>|<noncapgroup>|<lookarounds>
<union>          ::=            <RE>"|"<simple-RE>
<group>          ::=            "("<RE>")"
<eos>            ::=            "$"

<charclass>      ::=            <word>|<digit>
<word>           ::=            "\w"
<digit>          ::=            "\d"

<rangeU>         ::=            "A-Z"
<rangeL>         ::=            "a-z"

<char>           ::=            <character>|"\\"<metacharacter>|<metacharacter>
<set>            ::=            <positive-set>|<negative-set>
<positive-set>   ::=            "["<set-items>"]"
<negative-set>   ::=            "[^"<set-items>"]"
<set-items>      ::=            <set-item>|<set-item><set-items>
<set-item>       ::=            <range>|<char>
<range>          ::=            <char>"-"<char>
<metacharacter>  ::=             "!"|"""|"#"|"$"|"%"|"&"|"'"|"("|")"|"*"|"+"|","|"-"|"."|"/"|":"|";"|"<"|"="|">"|"?"|"@"|"["|"\\"|"]"|"^"|"_"|"`"|"{"|"}"|"~"
<character>       ::=            0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
