<RE>             ::=            <simple-RE>|<char>
<simple-RE>      ::=            <simple-RE><basic-RE>|<basic-RE>|<possessive>

<basic-RE>       ::=            <elementary-RE>|<char>

<possessive>     ::=            <elementary-RE>.|<elementary-RE>*+|<elementary-RE>++|<elementary-RE>?+|<RE>{<RE>,<RE>}+
<greedy>         ::=            <elementary-RE>*|<elementary-RE>+|<elementary-RE>?

<elementary-RE>  ::=            <RE>"|"<simple-RE>|(<RE>)|<char>|<set>|<charclass>|<range>|(?:<RE>)|<lookarounds>

<charclass>      ::=            \w|\d
<range>          ::=            [A-Z]|[a-z]
<char>           ::=            <character>|"\\"<metacharacter>|<metacharacter>
<lookarounds>    ::=            (?"<"=<RE>)|(?"<"!<RE>)|(?=<RE>)|(?!<RE>)
<set>            ::=            [<set-items>]|[^<set-items>]

<set-items>      ::=            <set-item>|<set-item><set-items>
<set-item>       ::=            <char>"-"<char>|<char>

<metacharacter>  ::=             "!"|"#"|"$"|"%"|"&"|"'"|"("|")"|"*"|"+"|","|"-"|"."|"/"|":"|";"|"<"|"="|">"|"?"|"@"|"["|"\\"|"]"|"^"|"_"|"`"|"{"|"}"|"~"|"|"|'"'
<character>       ::=            0|1|2|3|4|5|6|7|8|9|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
